languageCode = "en"
languageName = "English"
displayName = "🇬🇧"
isoCode = "en"
weight = 1
rtl = false

title = "gecco.xyz"
# logo = "img/gecco_round.png"
description = "gecco.xyz"
#copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"

[author]
  name = "Alexander Haas"
  image = "img/author.webp"
  headline = "Data Engineer @ shopping24"
  bio = "Data Engineer @ shopping24"
  links = [
    { github = "https://github.com/gecores" },
    { email = "mailto:contact@gecco.xyz" },
    { instagram = "https://instagram.com/gecco.xyz" },
    { linkedin = "https://www.linkedin.com/in/alexander-haas-244106193/" },
    { twitter = "https://twitter.com/geccoxyz" },
  ]
