languageCode = "en"
languageName = "English"
weight = 1
title = "gecco.xyz"

[params]
  displayName = "🇬🇧"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  # logo = "img/gecco_round.png"
  description = "gecco.xyz"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Alexander Haas"
  image = "img/author.webp"
  headline = "Data Engineer @ OTTO"
  bio = "Data Engineer @ OTTO"
  links = [
    { github = "https://github.com/gecores" },
    { email = "mailto:contact@gecco.xyz" },
    { instagram = "https://instagram.com/gecco.xyz" },
    { linkedin = "https://www.linkedin.com/in/alexander-haas-244106193/" },
    { twitter = "https://twitter.com/geccoxyz" },
  ]
